=== jawsu02/simple-project/src/test/resources/com/myo2/automation/schemaFiles/generateTokens.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "definitions": {},
  "id": "http://example.com/example.json",
  "items": {
    "id": "/items",
    "properties": {
      "DeviceId": {
        "default": "string",
        "description": "An explanation about the purpose of this instance.",
        "examples": [
          "string"
        ],
        "id": "/items/properties/DeviceId",
        "title": "The deviceid schema.",
        "type": "string"
      },
      "Href": {
        "default": "string",
        "description": "An explanation about the purpose of this instance.",
        "examples": [
          "string"
        ],
        "id": "/items/properties/Href",
        "title": "The href schema.",
        "type": "string"
      },
      "Status": {
        "default": "string",
        "description": "An explanation about the purpose of this instance.",
        "examples": [
          "string"
        ],
        "id": "/items/properties/Status",
        "title": "The status schema.",
        "type": "string"
      },
      "TokenId": {
        "default": 0,
        "description": "An explanation about the purpose of this instance.",
        "examples": [
          "0"
        ],
        "id": "/items/properties/TokenId",
        "title": "The tokenid schema.",
        "type": "integer"
      },
      "ValidFrom": {
        "default": "2017-10-20T07:48:05.493Z",
        "description": "An explanation about the purpose of this instance.",
        "examples": [
          "2017-10-20T07:48:05.493Z"
        ],
        "id": "/items/properties/ValidFrom",
        "title": "The validfrom schema.",
        "type": "string"
      },
      "ValidTo": {
        "default": "2017-10-20T07:48:05.493Z",
        "description": "An explanation about the purpose of this instance.",
        "examples": [
          "2017-10-20T07:48:05.493Z"
        ],
        "id": "/items/properties/ValidTo",
        "title": "The validto schema.",
        "type": "string"
      }
    },
    "type": "object"
  },
  "type": "array"
}

=== jawsu02/simple-project/src/test/resources/com/myo2/automation/responseFiles/generateTokens.json
[
  {
    "TokenId": 17246408,
    "DeviceId": "f07a13984f6d116a",
    "ValidFrom": "2018-02-08T00:00:00",
    "ValidTo": "2018-09-25T00:00:00",
    "Status": "Allocated",
    "Href": "http://uat-api-redemption.collinsonis.com/v1/member/8101105/token/17246408"
  },
  {
    "TokenId": 24042677,
    "DeviceId": "f07a13984f6d116a",
    "ValidFrom": "2018-02-08T00:00:00",
    "ValidTo": "2018-09-25T00:00:00",
    "Status": "Allocated",
    "Href": "http://uat-api-redemption.collinsonis.com/v1/member/8101105/token/24042677"
  },
  {
    "TokenId": 1007432,
    "DeviceId": "f07a13984f6d116a",
    "ValidFrom": "2018-02-08T00:00:00",
    "ValidTo": "2018-09-25T00:00:00",
    "Status": "Allocated",
    "Href": "http://uat-api-redemption.collinsonis.com/v1/member/8101105/token/1007432"
  },
  {
    "TokenId": 6705424,
    "DeviceId": "f07a13984f6d116a",
    "ValidFrom": "2018-02-08T00:00:00",
    "ValidTo": "2018-09-25T00:00:00",
    "Status": "Allocated",
    "Href": "http://uat-api-redemption.collinsonis.com/v1/member/8101105/token/6705424"
  },
  {
    "TokenId": 22742047,
    "DeviceId": "f07a13984f6d116a",
    "ValidFrom": "2018-02-08T00:00:00",
    "ValidTo": "2018-09-25T00:00:00",
    "Status": "Allocated",
    "Href": "http://uat-api-redemption.collinsonis.com/v1/member/8101105/token/22742047"
  },
  {
    "TokenId": 7290248,
    "DeviceId": "f07a13984f6d116a",
    "ValidFrom": "2018-02-08T00:00:00",
    "ValidTo": "2018-09-25T00:00:00",
    "Status": "Allocated",
    "Href": "http://uat-api-redemption.collinsonis.com/v1/member/8101105/token/7290248"
  },
  {
    "TokenId": 17079485,
    "DeviceId": "f07a13984f6d116a",
    "ValidFrom": "2018-02-08T00:00:00",
    "ValidTo": "2018-09-25T00:00:00",
    "Status": "Allocated",
    "Href": "http://uat-api-redemption.collinsonis.com/v1/member/8101105/token/17079485"
  },
  {
    "TokenId": 2626595,
    "DeviceId": "f07a13984f6d116a",
    "ValidFrom": "2018-02-08T00:00:00",
    "ValidTo": "2018-09-25T00:00:00",
    "Status": "Allocated",
    "Href": "http://uat-api-redemption.collinsonis.com/v1/member/8101105/token/2626595"
  },
  {
    "TokenId": 3873126,
    "DeviceId": "f07a13984f6d116a",
    "ValidFrom": "2018-02-08T00:00:00",
    "ValidTo": "2018-09-25T00:00:00",
    "Status": "Allocated",
    "Href": "http://uat-api-redemption.collinsonis.com/v1/member/8101105/token/3873126"
  },
  {
    "TokenId": 25120161,
    "DeviceId": "f07a13984f6d116a",
    "ValidFrom": "2018-02-08T00:00:00",
    "ValidTo": "2018-09-25T00:00:00",
    "Status": "Allocated",
    "Href": "http://uat-api-redemption.collinsonis.com/v1/member/8101105/token/25120161"
  }
]
